### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toJSON')

### ISSUE THREAD

**Issue by palmtown** [feathersjs-ecosystem/feathers-sync#186]
### Steps to reproduce

Prior to commit https://github.com/feathersjs-ecosystem/feathers-sync/commit/5106085cf1ceb7724991e3ebc0daac64e197efcc I was able to use ctx.service("myservice").emit("created", data) and that would work.  However, after the update, it no longer works.  The issue is created at service.emit (/usr/app/node_modules/feathers-sync/lib/core.js:55:46) as it does not check to ensure ctx is not undefined.

Is it now a requirement in features to pass the ctx as well when using service.emit?  In any case, should there be checking to ensure ctx is not undefined?  This seems to be the standard for other code in the same file.

### Expected behavior
Event emitted and synced successfully.

### Actual behavior
TypeError: Cannot read properties of undefined (reading 'toJSON')
    at service.emit (/usr/app/node_modules/feathers-sync/lib/core.js:55:46)

### System configuration

**Module versions** (especially the part that's not working): "3.0.2"

**Comment by palmtown** [comment]
Based on some of the documentation available, it does not require the context to be passed.  For example, at https://feathersjs.com/api/events.html, it has an example as show below that doesn't include the context as the third parameter.  However, if you follow this example and have feathers-sync enabled, you will get the same error as reported.

What would be the best path forward in this case?

`messages.emit('customEvent', {
  anything: 'Data can be anything'
})`

**Comment by palmtown** [comment]
Seems to be linked to this issue:  https://github.com/feathersjs/feathers/issues/3066

**Comment by palmtown** [comment]
If I add an empty object such as  messages.emit('customEvent', { anything: 'Data can be anything' }, {}) it will avoid the error.  However, it seems the fix is to check to see if ctx is undefined.

**Comment by palmtown** [comment]
I added an additional check that resolves and created a pull request at https://github.com/feathersjs-ecosystem/feathers-sync/pull/187.

**Comment by palmtown** [comment]
> If I add an empty object such as messages.emit('customEvent', { anything: 'Data can be anything' }, {}) it will avoid the error. However, it seems the fix is to check to see if ctx is undefined.

Just an F.Y.I., after further testing, if you try to pass an empty object as a third parameter, although the error goes away, feathers emit will not work and you will not receive events on the client side subscribed to the event.  The patch I submitted at https://github.com/feathersjs-ecosystem/feathers-sync/pull/187 solves the issue and makes feathers-sync compatiable with featherjs v5.
